---
- command: timedatectl set-timezone Asia/Seoul
- apt: name={{ item }}
  with_items:
  - python-pip
  - python-virtualenv
  - python-dev
  - build-essential
  - libpq-dev
  - htop
# for postgresql actions
- pip: name=psycopg2
